spring:
  config:
    activate:
      on-profile: oauth-dev

  oauth2:
    client:
      provider:
        naver:
          login-url: "https://nid.naver.com/oauth2.0/authorize"
          token-url: "https://nid.naver.com/oauth2.0/token"
          me-url: "https://openapi.naver.com/v1/nid/me"
        google:
          login-url: "https://accounts.google.com/o/oauth2/v2/auth"
          token-url: "https://oauth2.googleapis.com/token"
          resource-url: "https://www.googleapis.com/oauth2/v2/userinfo"
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          redirect-uri: "http://${BASE_URL}/api/auth/oauth/callback/google"
        naver:
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
          authorization-grant-type: authorization_code
          redirect-uri: "http://${BASE_URL}/api/auth/oauth/callback/naver"
