server:
  port: 8080

spring:
  application:
    name: nadul

  profiles:
    include: mysql, oauth
    group:
      "dev": "mysql-dev, oauth-dev"
    active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    database: mysql
    show-sql: true
    # generate-ddl: true
    #open-in-view: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true


cors:
  allowed-origins: '*'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600
