version: '3'
services:
  mysql-nadul:
    image: mysql:8.0
    container_name: mysql-nadul
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: naduldev
      MYSQL_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: nadul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - nadul-mysql-volume:/var/lib/mysql
  redis-nadul:
    image: redis:7.0
    container_name: redis-nadul
    ports:
      - "26379:6379"
    volumes:
      - nadul-redis-volume:/usr/local/etc/redis

volumes:
  nadul-mysql-volume:
    driver: local
  nadul-redis-volume:
    driver: local